### ISSUE TITLE
Enter problem

### ISSUE THREAD

**Issue by NovaHowl** [Thecakeisgit/Dckuino.js#12] opened 2016-11-17 08:01 UTC
When using the Enter command, it just types (

**Comment by Thecakeisgit** [comment] 2016-11-17 14:14
Hi @NovaHowl, please tell me what is you keyboard layout, it's caused by your layout..

**Comment by NovaHowl** [comment] 2016-11-17 19:29
Australian

**Comment by NovaHowl** [comment] 2016-11-17 19:30
Everything else works fine, just the enter command,

**Comment by NovaHowl** [comment] 2016-11-17 19:30
Thecakeisgit

**Comment by Thecakeisgit** [comment] 2016-11-17 19:48
*-* It's weird, @NovaHowl are u sure your Keyboard layout is exactly the same as US Keyboard layout ?

**Comment by NovaHowl** [comment] 2016-11-17 20:21
Yep, and I tried switching it to UK and it didn't work.

**Comment by Thecakeisgit** [comment] 2016-11-17 20:24
Hmm okay, and you used <b>Download Sketch!</b> button ?

**Comment by Thecakeisgit** [comment] 2016-11-17 20:24
@NovaHowl

**Comment by NovaHowl** [comment] 2016-11-17 20:26
Download sketch doesn't work for me. I also noticed I had to remove #include "Keyboard.h" @Thecakeisgit

**Comment by NovaHowl** [comment] 2016-11-17 20:27
Otherwise it would say (error compiling for Teensy 3.1/3.2

**Comment by Thecakeisgit** [comment] 2016-11-17 20:27
WTF, Hmm what's ur Arduino ide version ?

**Comment by Thecakeisgit** [comment] 2016-11-17 20:28
Are you on linux ? @NovaHowl

**Comment by NovaHowl** [comment] 2016-11-17 20:28
1.6.11 @Thecakeisgit

**Comment by NovaHowl** [comment] 2016-11-17 20:28
Nope

**Comment by Thecakeisgit** [comment] 2016-11-17 20:30
Okay, same version, @NovaHowl so it's maybe because you're trying to compile an Arduino code based on Arduino core for teensy.. Don't u think ?

**Comment by NovaHowl** [comment] 2016-11-17 20:31
Yeah maybe... Everything else in the converter works just fine tho

**Comment by NovaHowl** [comment] 2016-11-17 20:32
GUI r works, STRING works and everything else, but the ENTER function doesn't work. @Thecakeisgit

**Comment by Thecakeisgit** [comment] 2016-11-17 20:34
Okay, because with same thing with an Arduino mini, it works perfectly well.. But why the #include "Keyboard.h" fails... I don't know, it could be this..

**Comment by NovaHowl** [comment] 2016-11-17 20:35
When leaving #include "Keyboard.h"

In file included from C:\Users\Nova\AppData\Local\Temp\arduino_modified_sketch_60053\sketch_nov18a.ino:5:0:

C:\Program Files (x86)\Arduino\libraries\Keyboard\src/Keyboard.h:25:17: fatal error: HID.h: No such file or directory

 #include "HID.h"

                 ^

compilation terminated.

Error compiling for board Teensy 3.2 / 3.1.

**Comment by NovaHowl** [comment] 2016-11-17 20:38
@Thecakeisgit

**Comment by Thecakeisgit** [comment] 2016-11-17 20:41
Hmm, yes it's definitely because it's a teensy.. I'm sorry, but i think i can't help you @NovaHowl because i don't know teensy libs.. Sorry.. But if you find any solution, please tell me, I'll be interested.. ;D

Do you mind if i close the issue ?

**Comment by NovaHowl** [comment] 2016-11-17 20:42
Alright, that's fine. This is the only converter that came close to working with my Teensy 3.2. Anyways...

**Comment by Thecakeisgit** [comment] 2016-11-17 20:44
I'm sorry man, good night ;D @NovaHowl

**Comment by NovaHowl** [comment] 2016-11-17 20:45
Good night to you, good morning to me ;)

**Closed by Thecakeisgit** 2016-11-17 20:44 UTC

**Comment by crinny** [comment] 2018-08-19 06:55
Actually same.

**Comment by Nurrl** [comment] 2018-08-19 08:06
Hi @crinny, what is your Locale ?

**Comment by crinny** [comment] 2018-08-19 12:57
Russian

**Comment by JI8** [comment] 2018-12-12 19:12
Is there a fix for this problem? ''typeKey(KEY_RETURN);'' returns '')''.

**Comment by Nurrl** [comment] 2018-12-12 20:41
Again, you need to select a locale to be bundled with your code for it to work :) @JI8

**Comment by kenoc1** [comment] 2020-05-18 17:24
Hey, I have the same problem. ''typeKey(KEY_RETURN);'' returns '')'' What do you mean with select a locale to be bundled with your code @Nurrl ?

**Comment by Nurrl** [comment] 2020-05-19 09:28
I mean use this:
![rsz_screenshot_from_2020-05-19_11-25-47](https://user-images.githubusercontent.com/15341887/82309827-e8b3ee80-99c3-11ea-9964-d0b785715cf6.png)

**Comment by Nurrl** [comment] 2020-05-19 09:29
And select your locale, then try again to see if it works @kenoc1
