### ISSUE TITLE
Layout messed up using Firefox/Chrome

### ISSUE THREAD

**Issue by gh7531** [Thecakeisgit/Dckuino.js#13] opened 2016-11-22 17:18 UTC
Hello,
I tried to compile and download a script using the live version but if I load the page in Firefox or Chrome the layout of the page is messed up.
![brokenwebpage](https://cloud.githubusercontent.com/assets/9028609/20533958/b64cd536-b0df-11e6-81fe-40778c618640.png)

If I switch my useragent to a mobile device it looks fine.
![webpage](https://cloud.githubusercontent.com/assets/9028609/20533951/b140b9c2-b0df-11e6-86cb-8132efb983b5.png)

After I changed the useragent to default is get messed up again.

**Comment by Thecakeisgit** [comment] 2016-11-22 17:56
I'll try to fix this, but i can't reproduce the bug because i got a 4:3 screen.. Could you try on dev.cak3repo.xyz(Who is my test server) @gh7531 ? I tried a fix :)

**Comment by gh7531** [comment] 2016-11-22 18:12
Nope isn't working :( it looks the same.
![webpage](https://cloud.githubusercontent.com/assets/9028609/20535988/83be6fd2-b0e7-11e6-9021-0fb1308d5fda.png)

On my 4:3 second screen it's messed up to.

**Comment by Thecakeisgit** [comment] 2016-11-22 18:24
Hmm WTF, i can't reproduce it \*-\* @gh7531, have you updated your Firefox ?

**Comment by Thecakeisgit** [comment] 2016-11-22 18:26
Maybe your version doesn't support the css3 calc() function. @gh7531

**Comment by Thecakeisgit** [comment] 2016-11-22 18:30
What's you resolution ? @gh7531

**Comment by Thecakeisgit** [comment] 2016-11-22 18:52
Please retry @gh7531 https://dev.cak3repo.xyz

**Comment by gh7531** [comment] 2016-11-22 19:29
Still no luck :( 
I'm using FF 50.0 my resolution is 1920x1080.

While using the edge browser it's still messed up but not as badly
![wepage](https://cloud.githubusercontent.com/assets/9028609/20538643/63837144-b0f2-11e6-9749-69eb3543b889.png)

**Comment by Thecakeisgit** [comment] 2016-11-22 19:39
Okay, i'll wait to somebody else to send a comment here to really fix it \*-\* because i don't know what the fuck this is.. @gh7531 
@d4n5h Any idea ?

**Comment by ImaFridge** [comment] 2016-11-23 22:54
I've got the same problem as @gh7531 derp derp

**Comment by Thecakeisgit** [comment] 2016-11-24 17:05
Ok i'll fix it soon, i reinstalled my test server.. @gh7531 @ImaFridge

**Comment by KevinDenys** [comment] 2016-11-25 22:51
1920x1080 here running last version of chrome. No problems.

**Comment by Thecakeisgit** [comment] 2016-11-25 22:56
@KevinDenys I got no idea of what happenig with these guys.. I can't reproduce it, and i don't even know how to fix.. Any idea ? @KevinDenys

**Comment by KevinDenys** [comment] 2016-11-25 22:58
Can we get a screenshot of the console when the page is loaded @imafridge @gh7531

**Comment by gh7531** [comment] 2016-11-26 08:37
I'm not at home for the next 10 days so I can't provide the information I'm sorry. I'll do it as soon as I get home again.

**Comment by ImaFridge** [comment] 2016-11-26 15:21
![nvidia share_2016-11-26_16-19-49](https://cloud.githubusercontent.com/assets/23709056/20641250/577f408a-b3f4-11e6-98e9-b2fae6d5e09e.png)

**Comment by Thecakeisgit** [comment] 2016-11-26 15:29
Kinda weird, your Javascript console is saying something ? @ImaFridge

**Comment by KevinDenys** [comment] 2016-11-26 16:03
@ImaFridge thats the seytonic version. Can you try the https://thecakeisgit.github.io/Dckuino.js/

**Comment by KevinDenys** [comment] 2016-11-26 16:04
![image](https://cloud.githubusercontent.com/assets/17174443/20641526/5bd5d404-b3fa-11e6-89ed-bb93e86f0bff.png)
Firefox 1920x1080

**Comment by Thecakeisgit** [comment] 2016-11-26 16:11
572087d seems to fix it.. Try again please @ImaFridge :)

**Comment by ImaFridge** [comment] 2016-11-26 16:18
It works now! you guys rock <3
I used the Seytonic version bc i couldnt reacht the other site...

**Comment by Thecakeisgit** [comment] 2016-11-26 16:24
Thanks ! Fixed with 572087d.

**Closed by Thecakeisgit** 2016-11-26 16:24 UTC
Labels: graphical bug
